[supervisord]
nodaemon=true
logfile=/data/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:backend]
command=/usr/local/bin/nba_backend
directory=/data
environment=LOG_DIR="/data/log"
autostart=true
autorestart=true
stdout_logfile=/data/log/backend_stdout.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
stderr_logfile=/data/log/backend_stderr.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=5

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/data/log/nginx_stdout.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=3
stderr_logfile=/data/log/nginx_stderr.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=3
